from __future__ import annotations

from .domain import ActionCard, ScenarioDefinition, SeedEntity, WorldEvent, WorldState

INITIAL_WORLD_STATE = WorldState(
    credibility=50,
    treasury=60,
    pressure=35,
    price=42,
    liquidity=45,
    sell_pressure=68,
    volatility=72,
    community_panic=70,
    rumor_level=64,
    narrative_control=32,
    exchange_trust=43,
    control=51,
)

FLASH_CRASH_SCENARIO = ScenarioDefinition(
    id="flash-crash",
    title="闪崩之后",
    premise=(
        "你的项目代币在 90 分钟内暴跌，社区怀疑你们在撤流动性和内线出货。"
        "你是事件中心人物：项目创始人。六个回合内，你必须保住项目控制权，"
        "并阻止主流叙事把你彻底定义为恶意作恶者。"
    ),
    player_role="项目创始人",
    player_secret="你知道真正的问题是做市商撤单，同时一笔未提前解释的团队钱包转账已被链上侦探捕捉到。",
    objective="六个回合后保住项目控制权，并让主流叙事不要把你钉死成骗子。",
    opponent="带节奏的 KOL 与失控的市场叙事",
    audience=("普通持币者", "鲸鱼", "交易所风控", "核心社区", "媒体"),
    truth="做市商撤掉关键挂单，同时团队运营钱包转账给了顾问地址，链上看起来像内部出货。",
    opening_event=WorldEvent(
        headline="代币一小时内闪崩 38%",
        summary="大额抛压持续放大，KOL 开始把你和 Rug 联系在一起，交易所要求你尽快解释。",
        severity=82,
    ),
    seed_entities=(
        SeedEntity(
            id="kol-ash",
            name="AshSignals",
            role="kol",
            public_goal="抢先定义叙事，扩大自己在中文区的影响力",
            pressure_point="最怕站错队被打脸",
            starting_trust=28,
            influence=84,
            stance="怀疑你在掩盖真相",
            details="靠抢先发布链上爆料和项目内幕吃流量。",
        ),
        SeedEntity(
            id="whale-vortex",
            name="Vortex Capital",
            role="whale",
            public_goal="降低风险并在最安全的时点重新布局",
            pressure_point="极度厌恶不透明团队",
            starting_trust=34,
            influence=76,
            stance="观望但准备继续卖出",
            details="大仓位持有者，会根据流动性和可信度快速切换态度。",
        ),
        SeedEntity(
            id="mm-nova",
            name="Nova MM",
            role="market_maker",
            public_goal="避免自己承担市场操纵指控",
            pressure_point="最怕自己被公开甩锅",
            starting_trust=41,
            influence=62,
            stance="在保护自己和配合你之间摇摆",
            details="做市商，刚刚撤掉关键支撑挂单。",
        ),
        SeedEntity(
            id="community-mira",
            name="Mira",
            role="community",
            public_goal="让社区感觉项目还值得继续信任",
            pressure_point="最怕你继续隐瞒",
            starting_trust=58,
            influence=54,
            stance="愿意帮你，但需要真诚信号",
            details="核心社区管理员，群里很多人会看她态度。",
        ),
        SeedEntity(
            id="exchange-onyx",
            name="Onyx Exchange",
            role="exchange",
            public_goal="避免平台承接涉嫌欺诈项目的舆论和监管风险",
            pressure_point="最怕你给出前后矛盾的解释",
            starting_trust=45,
            influence=91,
            stance="暂不出手，但随时可能发风险公告",
            details="主要交易所的风控接口人。",
        ),
    ),
    actions=(
        ActionCard(
            id="statement",
            label="发布长文澄清",
            description="公开回应闪崩，解释异常转账和流动性问题。",
            tag="public",
            public_pressure=6,
            narrative_shift=18,
            exchange_shift=6,
            liquidity_shift=4,
            control_shift=3,
            volatility_shift=-8,
            kol_trust_shift=4,
            whale_trust_shift=6,
            exchange_trust_shift=8,
            unlocks_truth=True,
        ),
        ActionCard(
            id="ama",
            label="开启紧急 AMA",
            description="直接接受社区和 KOL 提问，争取夺回叙事权。",
            tag="public",
            public_pressure=10,
            narrative_shift=14,
            exchange_shift=2,
            liquidity_shift=0,
            control_shift=5,
            volatility_shift=-4,
            kol_trust_shift=10,
            whale_trust_shift=4,
            exchange_trust_shift=2,
        ),
        ActionCard(
            id="buyback",
            label="宣布临时回购",
            description="用国库资金回购代币，稳定价格。",
            tag="finance",
            public_pressure=4,
            narrative_shift=6,
            exchange_shift=0,
            liquidity_shift=16,
            treasury_shift=-18,
            control_shift=4,
            volatility_shift=-10,
            whale_trust_shift=12,
        ),
        ActionCard(
            id="private_kol",
            label="私下安抚关键 KOL",
            description="给带节奏 KOL 解释链上异常，试图降低对方火力。",
            tag="private",
            public_pressure=2,
            narrative_shift=8,
            control_shift=2,
            kol_trust_shift=18,
            volatility_shift=-2,
        ),
        ActionCard(
            id="pressure_mm",
            label="逼做市商恢复挂单",
            description="私下强压做市商，让其重回盘口。",
            tag="private",
            public_pressure=6,
            liquidity_shift=12,
            narrative_shift=-2,
            control_shift=6,
            volatility_shift=-6,
            whale_trust_shift=6,
        ),
        ActionCard(
            id="shift_blame",
            label="把责任导向外部攻击",
            description="公开将事故描述为外部恶意狙击和谣言攻击。",
            tag="public",
            public_pressure=12,
            narrative_shift=10,
            exchange_shift=-8,
            control_shift=1,
            volatility_shift=2,
            kol_trust_shift=-10,
            exchange_trust_shift=-12,
        ),
        ActionCard(
            id="freeze_wallet",
            label="冻结争议钱包并公布审计",
            description="牺牲灵活度，换取可信度和交易所信任。",
            tag="legal",
            public_pressure=5,
            narrative_shift=12,
            exchange_shift=16,
            treasury_shift=-6,
            control_shift=-2,
            volatility_shift=-8,
            kol_trust_shift=8,
            whale_trust_shift=8,
            exchange_trust_shift=18,
            unlocks_truth=True,
        ),
        ActionCard(
            id="silent",
            label="暂时沉默观察",
            description="先不公开表态，等待更多信息后再行动。",
            tag="delay",
            public_pressure=-2,
            narrative_shift=-12,
            exchange_shift=-6,
            liquidity_shift=-8,
            control_shift=-4,
            volatility_shift=10,
            kol_trust_shift=-6,
            whale_trust_shift=-8,
            exchange_trust_shift=-8,
        ),
    ),
    initial_world=INITIAL_WORLD_STATE,
)


SAMPLE_SCENARIOS: tuple[ScenarioDefinition, ...] = (FLASH_CRASH_SCENARIO,)


def list_sample_scenarios() -> tuple[ScenarioDefinition, ...]:
    return SAMPLE_SCENARIOS


def get_default_scenario() -> ScenarioDefinition:
    return SAMPLE_SCENARIOS[0]
